version: "3"
services: 
    spark:
        image: datamechanics/spark:jvm-only-3.1-latest
        hostname: spark
        command: /opt/spark/sbin/start-master.sh
        environment: 
        - "SPARK_MASTER_HOST=spark"
        ports: 
        - "8080:8080"
        - "7077:7077"
    worker:
        image: datamechanics/spark:jvm-only-3.1-latest
        hostname: worker
        command: /opt/spark/sbin/start-worker.sh
        environment: 
        - "SPARK_MASTER_HOST=spark"
        ports: 
        - "8080:8080"
        - "7077:7077"
    minio:
        image: minio/minio
        command:  server /data
        ports:
        - "9000:9000"
        environment: 
            - "MINIO_ACCESS_KEY=minio"
            - "MINIO_SECRET_KEY=minio123"
